#!/bin/sh

# Copyright (c) 2012-2015 General Electric Company. All rights reserved."
# The copyright to the computer software herein is the property of"
# General Electric Company. The software may be used and/or copied only"
# with the written permission of General Electric Company or in accordance"
# with the terms and conditions stipulated in the agreement/contract"
# under which the software has been supplied"


#
# There must be an argument for the downloaded eclipse.tar.gz
# 
MACHINE_BUILD_VERSION=15.3.0

if [ -e "$HOME/.mbsruntime" ]; then 
    echo "The file $HOME/.mbsruntime must not exist. Please rename or remove it."
    exit 1
fi

Usage () {
    echo "GenerateContainers [path to the downloaded eclipse.tar.gz] [Type of container]"
    echo "        Type of containers options:  -PROV | -DEBUG | -FCS | -BB | -STS | -CUSTOM <img file path> | [not specified]"
    echo "        If [Type of container] not specified then create default Predix Machine container"
    exit 1
}

if [ -z "$1" ]; then
    echo "####################  E R R O R ######################"
    echo "No eclipse.tar.gz supplied"
    echo "####################  E R R O R ######################"
    Usage
elif [ "$1" = "?" ] || [ "$1" = "-usage" ]; then
    Usage
fi
if [ ! -e "$1" ]; then 
    echo "####################  E R R O R ######################"
    echo "eclipse.tar.gz not found"
    echo "####################  E R R O R ######################"
    Usage
fi


if [ "$2" = "-PROV" ]; then
    mvn clean install -Declipse.archive="$1"
    mvn exec:exec -Dimage.file=tid_predix-provision.img -Doutput.folder=PredixMachine-provision-$MACHINE_BUILD_VERSION 
elif [ "$2" = "-DEBUG" ]; then
    mvn clean install -Declipse.archive="$1"
    mvn exec:exec -Dimage.file=tid_predix-full.img -Doutput.folder=PredixMachine-debug-$MACHINE_BUILD_VERSION 
elif [ "$2" = "-FCS" ]; then
    mvn clean install -Declipse.archive="$1"
    mvn exec:exec -Dimage.file=tid_predix-fcs.img -Doutput.folder=FCS-$MACHINE_BUILD_VERSION 
elif [ "$2" = "-BB" ]; then
	mvn clean install -Declipse.archive="$1"
	mvn exec:exec -Dimage.file=tid_predix-busbridge.img -Doutput.folder=BusBridge-$MACHINE_BUILD_VERSION 
elif [ "$2" = "-STS" ]; then
	mvn clean install -Declipse.archive="$1"
	mvn exec:exec -Dimage.file=tid_predix-sts.img -Doutput.folder=STS-$MACHINE_BUILD_VERSION
elif [ "$2" = "-CUSTOM" ]; then
    if [ ! -z "$3" ]; then
        if [ -r "$3" ]; then
            mvn clean install -Declipse.archive="$1"
            mvn exec:exec -Dimage.file="$(basename $3)" -Doutput.folder=PredixMachine-$(basename $3)-$MACHINE_BUILD_VERSION -Dimage.folder="$(dirname $3)"
        else
            echo "####################  E R R O R ######################"
            echo "File $3 could not be read. Please provide the path to a valid custom image file"
            echo "######################################################"
            Usage
        fi
    else
        echo "####################  E R R O R ######################"
        echo "Please provide the path to your custom image file"
        echo "######################################################"
        Usage
    fi 
elif  [ -z "$2" ]; then
	mvn clean install -Declipse.archive="$1"
	mvn exec:exec -Dimage.file=tid_predix-release.img -Doutput.folder=PredixMachine-$MACHINE_BUILD_VERSION 
else
	echo "####################  E R R O R ######################"
	echo "Please provide a valid container type"
	echo "######################################################"
	Usage
fi
