#!/bin/bash
#
#   Copyright (c) 2012-2015 General Electric Company. All rights reserved.
#
#   The copyright to the computer software herein is the property of
#   General Electric Company. The software may be used and/or copied only
#   with the written permission of General Electric Company or in accordance
#   with the terms and conditions stipulated in the agreement/contract
#   under which the software has been supplied.
#
#   Script for starting Http Tunnel Server

# You can override the following settings with the correct location of Java
JAVA=`which java`

# Make sure JAVA is set correctly.
test -z "$JAVA" && echo "java not found" && exit 0

# Build classpath
CLASSPATH=":lib/*"

# Application to be run
APP_NAME=com.ge.dspmicro.httptunnel.server.app.ServerHttpTunnelServerMain

# Params: Server Port, Keystore file location, keystore type
SERVER_PORT=
KEYSTORE_FILE=
KEYSTORE_TYPE=

# Run publish
$JAVA -classpath $CLASSPATH $APP_NAME $SERVER_PORT $KEYSTORE_FILE $KEYSTORE_TYPE